const settings = require('./settings')

module.exports = function renderQrPage() {
  return [
    '<!DOCTYPE html>',
    '<html lang="fr">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>SLAPET BOT QR</title>',
    '  <style>',
    '    * { box-sizing: border-box; }',
    '    body {',
    '      margin: 0;',
    '      min-height: 100vh;',
    '      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
    '      background: #090b12;',
    '      color: #e6edf7;',
    '      display: flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      padding: 1.5rem;',
    '    }',
    '    .container {',
    '      width: min(100%, 560px);',
    '      background: rgba(255,255,255,0.06);',
    '      border: 1px solid rgba(255,255,255,0.12);',
    '      border-radius: 24px;',
    '      padding: 1.75rem;',
    '      box-shadow: 0 24px 80px rgba(0,0,0,0.35);',
    '    }',
    '    h1 { margin: 0 0 1rem; font-size: 2rem; }',
    '    p { margin: 0 0 1rem; color: rgba(255,255,255,0.75); }',
    '    .link { color: #66d9ef; text-decoration: none; }',
    '    .qr-card {',
    '      margin-top: 1rem;',
    '      padding: 1rem;',
    '      background: rgba(255,255,255,0.05);',
    '      border-radius: 18px;',
    '      border: 1px solid rgba(255,255,255,0.12);',
    '      min-height: 280px;',
    '      display: grid;',
    '      place-items: center;',
    '    }',
    '    .qr-card img {',
    '      width: 100%;',
    '      max-width: 320px;',
    '      height: auto;',
    '    }',
    '    .status {',
    '      margin-top: 1rem;',
    '      padding: 1rem;',
    '      border-radius: 16px;',
    '      background: rgba(255,255,255,0.06);',
    '      border: 1px solid rgba(255,255,255,0.12);',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="container">',
    '    <h1>SLAPET BOT QR</h1>',
    '    <p>Scanne ce QR avec WhatsApp pour connecter le bot. Si aucun QR ne s’affiche, attends que le bot se reconnecte.</p>',
    '    <p><a class="link" href="/">Retour à la page de pairing</a></p>',
    '    <div class="qr-card" id="qrCard">Chargement du QR...</div>',
    '    <div class="status" id="qrStatus">Statut en cours...</div>',
    '  </div>',
    '  <script>',
    '    const qrCard = document.getElementById("qrCard");',
    '    const qrStatus = document.getElementById("qrStatus");',
    '    const refreshQr = async () => {',
    '      try {',
    '        const res = await fetch("/qr-json");',
    '        const data = await res.json();',
    '        if (!res.ok) {',
    '          qrCard.textContent = data.error || "QR non disponible.";',
    '          qrStatus.textContent = "Attends la génération du QR sur le bot.";',
    '          return;',
    '        }',
    '        qrCard.innerHTML = `<img src="${data.qr}" alt="QR Code" />`;',
    '        qrStatus.textContent = "QR prêt. Scanne-le avec WhatsApp.";',
    '      } catch (err) {',
    '        qrCard.textContent = "Impossible de charger le QR.";',
    '        qrStatus.textContent = "Vérifie que le bot est en cours d’exécution.";',
    '      }',
    '    };',
    '    refreshQr();',
    '    setInterval(refreshQr, 5000);',
    '  </script>',
    '</body>',
    '</html>',
  ].join("\n");
}
