module.exports = function renderHomePage() {
  return [
    '<!DOCTYPE html>',
    '<html lang="fr">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>SLAPET BOT Pairing</title>',
    '  <style>',
    '    * { box-sizing: border-box; }',
    '    :root {',
    '      color-scheme: dark;',
    '      --bg: #090b12;',
    '      --panel: rgba(20, 27, 44, 0.95);',
    '      --surface: rgba(255, 255, 255, 0.04);',
    '      --border: rgba(255, 255, 255, 0.08);',
    '      --text: #e6edf7;',
    '      --muted: #9fb3cc;',
    '      --primary: #7b9eff;',
    '      --accent: #66d9ef;',
    '      --success: #5fdcd8;',
    '      --danger: #f46c75;',
    '      --shadow: 0 28px 80px rgba(0, 0, 0, 0.35);',
    '    }',
    '    html, body {',
    '      margin: 0;',
    '      min-height: 100%;',
    '      font-family: Inter, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
    '      background: radial-gradient(circle at top, rgba(112, 125, 255, 0.12), transparent 25%), radial-gradient(circle at 20% 10%, rgba(102, 217, 239, 0.08), transparent 20%), var(--bg);',
    '      color: var(--text);',
    '    }',
    '    body {',
    '      display: flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      padding: 2rem;',
    '    }',
    '    .container {',
    '      width: min(100%, 900px);',
    '      padding: 2rem;',
    '      border-radius: 32px;',
    '      background: linear-gradient(180deg, rgba(18, 26, 49, 0.98), rgba(14, 20, 38, 0.98));',
    '      border: 1px solid var(--border);',
    '      box-shadow: var(--shadow);',
    '      backdrop-filter: blur(20px);',
    '    }',
    '    .topbar {',
    '      display: flex;',
    '      justify-content: space-between;',
    '      flex-wrap: wrap;',
    '      gap: 1rem;',
    '      align-items: center;',
    '    }',
    '    .brand {',
    '      display: grid;',
    '      gap: 0.4rem;',
    '    }',
    '    .brand h1 {',
    '      margin: 0;',
    '      font-size: clamp(2rem, 2.5vw, 2.8rem);',
    '      letter-spacing: -0.04em;',
    '    }',
    '    .brand p {',
    '      margin: 0;',
    '      color: var(--muted);',
    '      max-width: 520px;',
    '    }',
    '    .status-pill {',
    '      padding: 0.85rem 1.4rem;',
    '      border-radius: 999px;',
    '      border: 1px solid rgba(255,255,255,0.12);',
    '      background: rgba(255,255,255,0.035);',
    '      color: var(--success);',
    '      font-weight: 700;',
    '    }',
    '    .grid {',
    '      display: grid;',
    '      gap: 1.5rem;',
    '      margin-top: 2rem;',
    '    }',
    '    .card {',
    '      padding: 1.6rem;',
    '      border-radius: 24px;',
    '      background: var(--surface);',
    '      border: 1px solid var(--border);',
    '      box-shadow: inset 0 0 0 1px rgba(255,255,255,0.02);',
    '    }',
    '    .card h2 {',
    '      margin: 0 0 1rem;',
    '      font-size: 1.05rem;',
    '      letter-spacing: -0.02em;',
    '    }',
    '    .card p {',
    '      margin: 0;',
    '      color: var(--muted);',
    '      line-height: 1.7;',
    '    }',
    '    .input-group {',
    '      display: grid;',
    '      gap: 1rem;',
    '    }',
    '    input[type="text"] {',
    '      width: 100%;',
    '      border: 1px solid rgba(255,255,255,0.08);',
    '      border-radius: 18px;',
    '      padding: 1rem 1.1rem;',
    '      background: rgba(255,255,255,0.03);',
    '      color: var(--text);',
    '      font-size: 1rem;',
    '    }',
    '    input[type="text"]::placeholder {',
    '      color: rgba(255,255,255,0.45);',
    '    }',
    '    button {',
    '      display: inline-flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      padding: 1rem 1.4rem;',
    '      border: none;',
    '      border-radius: 18px;',
    '      background: linear-gradient(135deg, rgba(123, 158, 255, 0.95), rgba(102, 217, 239, 0.95));',
    '      color: #071a35;',
    '      font-weight: 700;',
    '      cursor: pointer;',
    '      transition: transform 0.25s ease, box-shadow 0.25s ease;',
    '    }',
    '    button:hover {',
    '      transform: translateY(-1px);',
    '      box-shadow: 0 18px 40px rgba(102, 217, 239, 0.2);',
    '    }',
    '    .output {',
    '      min-height: 4.5rem;',
    '      display: flex;',
    '      align-items: center;',
    '      padding: 1rem 1.2rem;',
    '      border-radius: 20px;',
    '      background: rgba(255,255,255,0.03);',
    '      border: 1px solid rgba(255,255,255,0.08);',
    '      color: var(--text);',
    '      font-size: 1rem;',
    '      gap: 0.5rem;',
    '    }',
    '    .badge {',
    '      display: inline-flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      padding: 0.4rem 0.75rem;',
    '      border-radius: 999px;',
    '      background: rgba(102, 217, 239, 0.12);',
    '      color: var(--accent);',
    '      font-size: 0.95rem;',
    '      font-weight: 700;',
    '    }',
    '    .code-box {',
    '      position: relative;',
    '      padding: 1rem;',
    '      margin-top: 1rem;',
    '      border-radius: 18px;',
    '      background: rgba(255,255,255,0.05);',
    '      border: 1px solid rgba(255,255,255,0.1);',
    '      color: var(--text);',
    '      display: grid;',
    '      gap: 0.75rem;',
    '    }',
    '    .code-text {',
    '      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;',
    '      font-size: 1.05rem;',
    '      word-break: break-all;',
    '    }',
    '    .copy-button {',
    '      justify-self: start;',
    '      padding: 0.75rem 1rem;',
    '      border-radius: 14px;',
    '      border: none;',
    '      background: rgba(123, 158, 255, 0.95);',
    '      color: #071a35;',
    '      font-weight: 700;',
    '      cursor: pointer;',
    '    }',
    '    .copy-button:hover {',
    '      transform: translateY(-1px);',
    '    }',
    '    .footer {',
    '      margin-top: 2rem;',
    '      display: grid;',
    '      gap: 0.75rem;',
    '      color: var(--muted);',
    '      font-size: 0.95rem;',
    '    }',
    '    .footer a {',
    '      color: var(--text);',
    '      text-decoration: none;',
    '      border-bottom: 1px dashed rgba(255,255,255,0.25);',
    '    }',
    '    @media (max-width: 640px) { .container { padding: 1.5rem; } .topbar { gap: 1rem; } }',
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="container">',
    '    <div class="topbar">',
    '      <div class="brand">',
    '        <h1>SLAPET BOT Pairing</h1>',
    '        <p>Connecte ton compte WhatsApp avec le bot via un code sécurisé. Interface moderne et épurée, servie depuis Node.</p>',
    '      </div>',
    '      <div class="status-pill" id="connectionStatus">Chargement...</div>',
    '    </div>',
    '    <div class="grid">',
    '      <div class="card">',
    '        <h2>✓ Vérifier le statut</h2>',
    '        <p>Le bot côté serveur doit être connecté pour générer le code. Le site affiche le code généré par le bot et indique où le saisir dans WhatsApp.</p>',
    '      </div>',
    '      <div class="card">',
    '        <h2>✓ Générer le code</h2>',
    '        <div class="input-group">',
    '          <label for="number">Numéro WhatsApp international</label>',
    '          <input id="number" type="text" placeholder="22892864375">',
    '          <button id="requestButton" type="button">Obtenir le code</button>',
    '        </div>',
    '        <p style="margin-top: 0.75rem; color: var(--muted); font-size: 0.92rem;">Saisis ton numéro sans + ni espaces, puis clique. Le site affichera le code de pairing généré par le bot.</p>',
    '      </div>',
    '      <div class="card">',
    '        <h2>✓ Résultat</h2>',
    '        <div class="output" id="status">Chargement du statut du bot...</div>',
    '        <div class="output" id="pairingOutput" style="margin-top: 1rem; min-height: 3rem;">Le code de pairing s’affichera ici après avoir cliqué sur le bouton.</div>',
    '        <div class="output" id="debugLog" style="margin-top: 1rem; font-size: 0.95rem; max-height: 5rem; overflow:auto; color: var(--muted); background: rgba(255,255,255,0.02); border-color: rgba(255,255,255,0.05);">Logs de débogage visibles ici</div>',
    '      </div>',
    '    </div>',
    '    <div class="footer">',
    '      <p>Cette interface est servie entièrement par Node via Express. Aucune ressource HTML/CSS externe n’est requise.</p>',
    '      <p>Dans WhatsApp : Appareils liés → Lier un appareil → entrer le code.</p>',
    '      <p style="color: var(--muted); font-size: 0.88rem; margin-top: 0.75rem;">Developed by JOE SLAPET</p>',
    '    </div>',
    '  </div>',
    '  <script>',
    '    const statusBox = document.getElementById("status");',
    '    const connectionPill = document.getElementById("connectionStatus");',
    '    const requestButton = document.getElementById("requestButton");',
    '    const numberInput = document.getElementById("number");',
    '    const pairingOutput = document.getElementById("pairingOutput");',
    '    const debugLog = document.getElementById("debugLog");',
    '    async function refreshStatus() {',
    '      try {',
    '        const res = await fetch("/status");',
    '        const data = await res.json();',
    '        connectionPill.textContent = data.connected ? "Bot prêt" : "Bot indisponible";',
    '        connectionPill.style.color = data.connected ? "#0d1829" : "#f46c75";',
    '        connectionPill.style.background = data.connected ? "rgba(97, 227, 221, 0.16)" : "rgba(244, 108, 117, 0.16)";',
    '        statusBox.innerHTML = "<span class=\"badge\">Connexion</span> " + (data.connected ? "en ligne" : "hors ligne") + "<br><span class=\"badge\">Enregistré</span> " + (data.registered ? "oui" : "non") + "<br><span class=\"badge\">Utilisateur</span> " + (data.user || "aucun");',
    '        if (!data.connected) {',
    '          statusBox.innerHTML += "<br><span class=\"badge\">Info</span> Attente du bot...";',
    '        } else if (data.registered) {',
    '          statusBox.innerHTML += "<br><span class=\"badge\">Info</span> Le bot est déjà enregistré. Réinitialisez la session.";',
    '        } else {',
    '          statusBox.innerHTML += "<br><span class=\"badge\">Info</span> Le bot est prêt pour générer le code.";',
    '        }',
    '        debugLog.textContent = "Status debug: " + JSON.stringify(data);',
    '      } catch (err) {',
    '        connectionPill.textContent = "Erreur réseau";',
    '        connectionPill.style.color = "#f46c75";',
    '        connectionPill.style.background = "rgba(244, 108, 117, 0.16)";',
    '        statusBox.innerText = "Impossible de joindre le bot. Vérifie que le service est démarré.";',
    '        debugLog.textContent = "Erreur de statut: " + (err.message || err);',
    '      }',
    '    }',
    '    window.addEventListener("error", (event) => {',
    '      debugLog.textContent = "Erreur JS: " + event.message;',
    '    });',
    '    window.addEventListener("unhandledrejection", (event) => {',
    '      const reason = event.reason && event.reason.message ? event.reason.message : event.reason;',
    '      debugLog.textContent = "Promise rejetée: " + reason;',
    '    });',
    '    requestButton.addEventListener("click", async () => {',
    '      const number = numberInput.value.trim();',
    '      if (!number) return alert("Merci de saisir un numéro");',
    '      statusBox.textContent = "Demande en cours...";',
    '      pairingOutput.innerHTML = "<div class=\"code-box\"><div class=\"code-text\">Recherche du code...</div></div>";',
    '      debugLog.textContent = "";',
    '      try {',
    '        const res = await fetch("/code?number=" + encodeURIComponent(number));',
    '        const data = await res.json();',
    '        debugLog.textContent = "HTTP " + res.status + " — response: " + JSON.stringify(data);',
    '        if (!res.ok) throw new Error((data.error || "Erreur serveur") + " (HTTP " + res.status + ")");',
    '        const codeValue = data.code || "Aucun code reçu";',
    '        pairingOutput.innerHTML = "<div class=\"code-box\"><div class=\"code-text\">" + codeValue + "</div><button class=\"copy-button\" id=\"copyCodeButton\">Copier le code</button><div style=\"font-size:0.92rem;color:var(--muted);\">Colle ce code dans WhatsApp → Appareils liés → Lier un appareil.</div></div>";',
    '        const copyButton = document.getElementById("copyCodeButton");',
    '        if (copyButton) {',
    '          copyButton.addEventListener("click", () => {',
    '            navigator.clipboard.writeText(codeValue).then(() => {',
    '              copyButton.textContent = "Copié";',
    '            }).catch(() => {',
    '              copyButton.textContent = "Échec";',
    '            });',
    '          });',
    '        }',
    '      } catch (err) {',
    '        pairingOutput.innerHTML = "<div class=\"code-box\"><span class=\"badge\">Erreur</span> " + (err.message || "Impossible de récupérer le code") + "</div>";',
    '        debugLog.textContent = "Détail: " + (err.stack || err.message);',
    '      }',
    '    });',
    '    refreshStatus();',
    '    setInterval(refreshStatus, 10000);',
    '  </script>',
    '</body>',
    '</html>'
  ].join('');
}
