const settings = require('./settings')

module.exports = function renderHomePage() {
  return [
    '<!DOCTYPE html>',
    '<html lang="fr">',
    '<head>',
    '  <meta charset="UTF-8">',
    '  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
    '  <title>SLAPET BOT Pairing</title>',
    '  <style>',
    '    * { box-sizing: border-box; }',
    '    body {',
    '      margin: 0;',
    '      min-height: 100vh;',
    '      font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;',
    '      background: #090b12;',
    '      color: #e6edf7;',
    '      display: flex;',
    '      align-items: center;',
    '      justify-content: center;',
    '      padding: 1.5rem;',
    '    }',
    '    .container {',
    '      width: min(100%, 520px);',
    '      background: rgba(255,255,255,0.06);',
    '      border: 1px solid rgba(255,255,255,0.12);',
    '      border-radius: 24px;',
    '      padding: 1.75rem;',
    '      box-shadow: 0 24px 80px rgba(0,0,0,0.35);',
    '    }',
    '    h1 { margin: 0 0 1rem; font-size: 2rem; }',
    '    p { margin: 0 0 1rem; color: rgba(255,255,255,0.75); line-height: 1.5; }',
    '    .small { font-size: 0.92rem; color: rgba(255,255,255,0.6); margin-bottom: 1rem; }',
    '    input {',
    '      width: 100%;',
    '      padding: 1rem;',
    '      border-radius: 16px;',
    '      border: 1px solid rgba(255,255,255,0.14);',
    '      background: rgba(255,255,255,0.04);',
    '      color: #fff;',
    '      font-size: 1rem;',
    '      margin-bottom: 1rem;',
    '    }',
    '    button {',
    '      width: 100%;',
    '      padding: 1rem;',
    '      border: none;',
    '      border-radius: 16px;',
    '      background: linear-gradient(135deg, #7b9eff, #66d9ef);',
    '      color: #071a35;',
    '      font-weight: 700;',
    '      cursor: pointer;',
    '    }',
    '    .output {',
    '      margin-top: 1rem;',
    '      padding: 1rem;',
    '      border-radius: 16px;',
    '      background: rgba(255,255,255,0.06);',
    '      border: 1px solid rgba(255,255,255,0.12);',
    '      min-height: 3rem;',
    '      display: flex;',
    '      align-items: center;',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    '  <div class="container">',
    '    <h1>SLAPET BOT Pairing</h1>',
    '    <p>Le propriétaire du bot est fixe et défini dans le fichier <code>settings.js</code>. Le numéro saisi ici est celui de l’utilisateur que tu veux connecter.</p>',
    `    <p class="small">Propriétaire : ${settings.ownerNumber}</p>`,
    '    <input id="number" type="text" placeholder="228XXXXXXXX" autocomplete="off">',
    '    <button id="requestButton" type="button">Obtenir le code</button>',
    '    <div class="output" id="statusOutput">Chargement de l’état du bot...</div>',
    '    <div class="output" id="qrOutput">QR non disponible</div>',
    '    <div class="output" id="pairingOutput">Entrez un numéro puis cliquez sur le bouton.</div>',
    '  </div>',
    '  <script>',
    '    const requestButton = document.getElementById("requestButton");',
    '    const numberInput = document.getElementById("number");',
    '    const pairingOutput = document.getElementById("pairingOutput");',
    '    const statusOutput = document.getElementById("statusOutput");',
    '    const qrOutput = document.getElementById("qrOutput");',
    '    const updateStatus = async () => {',
    '      try {',
    '        const res = await fetch("/status");',
    '        const data = await res.json();',
    '        let statusText = `<strong>Bot:</strong> ${data.connectionState || "inconnu"}`;',
    '        if (data.connectionState === "qr") {',
    '          statusText = `<strong>Bot:</strong> QR généré, scannez WhatsApp pour connecter.`;',
    '        } else if (data.connectionState === "connecting") {',
    '          statusText = `<strong>Bot:</strong> En connexion...`;',
    '        } else if (data.connectionState === "reconnecting") {',
    '          statusText = `<strong>Bot:</strong> En reconnexion...`;',
    '        } else if (data.connectionState === "open") {',
    '          statusText = `<strong>Bot:</strong> Connecté`;',
    '        } else if (data.connectionState === "loggedOut") {',
    '          statusText = `<strong>Bot:</strong> Session déconnectée. Ré-authentification requise.`;',
    '        }',
    '        if (data.registered) statusText += " (déjà enregistré)";',
    '        statusOutput.innerHTML = statusText;',
    '        if (data.connectionState === "qr") {',
    '          qrOutput.innerHTML = `<a href="/qr" style="color:#66d9ef; text-decoration:none;">QR disponible — ouvrir la page QR</a>`;',
    '        } else {',
    '          qrOutput.textContent = data.connectionState === "qr" ? "QR disponible, actualisez si nécessaire." : "QR non disponible";',
    '        }',
    '        if (data.lastDisconnect) {',
    '          const reason = data.lastDisconnect.error?.output?.statusCode || data.lastDisconnect.reason || data.lastDisconnect.error || JSON.stringify(data.lastDisconnect)',
    '          statusOutput.innerHTML += `<br><small style="display:block;color:#ff8080; margin-top:.5rem;">Dernière fermeture : ${reason}</small>`;',
    '        }',
    '        const isConnecting = data.connectionState === "connecting" && !data.registered;',
    '        const isOpen = data.connectionState === "open" && !data.registered;',
    '        const isQr = data.connectionState === "qr" && !data.registered;',
    '        const isReady = isOpen; // require open to enable code generation',
    '        requestButton.disabled = !isReady;',
    '        if (isQr) {',
    '          requestButton.textContent = "Le bot a un QR : scannez /qr pour authentifier, puis revenez";',
    '        } else {',
    '          requestButton.textContent = isReady ? "Obtenir le code" : "Le bot doit être connecté (open)";',
    '        }',
    '        if (data.lastPairing && data.lastPairing.code) {',
    '          pairingOutput.innerHTML = `<strong>Dernier code :</strong> ${data.lastPairing.code} <small style="opacity:.85; margin-left:.5rem">pour ${data.lastPairing.number}</small>`;',
    '        } else {',
    '          if (!pairingOutput.innerHTML || pairingOutput.innerHTML.includes("Entrez un numéro")) {',
    '            pairingOutput.textContent = "Entrez un numéro puis cliquez sur le bouton.";',
    '          }',
    '        }',
    '        if (!data.connectionState) {',
    '          statusOutput.innerHTML = "État du bot indisponible.";',
    '        }',
    '      } catch (err) {',
    '        statusOutput.textContent = "Impossible de joindre le statut du bot.";',
    '        qrOutput.textContent = "QR non disponible";',
    '        requestButton.disabled = true;',
    '        requestButton.textContent = "Connexion indisponible";',
    '      }',
    '    };',
    '    requestButton.addEventListener("click", async () => {',
    '      const number = numberInput.value.trim().replace(/[^0-9]/g, "");',
    '      if (!number) {',
    '        pairingOutput.textContent = "Merci de saisir un numéro valide.";',
    '        return;',
    '      }',
    '      pairingOutput.textContent = "Génération en cours...";',
    '      try {',
    '        const res = await fetch("/code?number=" + encodeURIComponent(number));',
    '        const data = await res.json();',
    '        if (!res.ok) {',
    '          pairingOutput.textContent = "Erreur : " + (data.error || "Impossible de générer le code.");',
    '        } else {',
    '          const code = data.code || "Aucun code reçu";',
    '          pairingOutput.innerHTML = `<strong>Code :</strong> ${code}`;',
    '        }',
    '      } catch (err) {',
    '        pairingOutput.textContent = "Erreur réseau. Vérifiez que le serveur est bien démarré.";',
    '      }',
    '    });',
    '    updateStatus();',
    '    setInterval(updateStatus, 5000);',
    '  </script>',
    '</body>',
    '</html>',
  ].join("\n");
}
